# Generated by Django 3.2.9 on 2021-11-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_total_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
